name: Deploy static HTML site to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔥 Environment'dan config.js oluştur
      - name: Create config.js
        run: |
          echo "window.env = {" > ./config.js
          echo "  SUPABASE_URL: '${{ vars.SUPABASE_URL }}'," >> ./config.js
          echo "  SUPABASE_ANON_KEY: '${{ vars.SUPABASE_ANON_KEY }}'" >> ./config.js
          echo "};" >> ./config.js
          cat config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4